service: aws-lambda-crud-node
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: 'us-west-2'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:421626112766:table/ClientsTable

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  createClient:
    handler: src/client.createClient
    events:
      - httpApi:
          path: /client
          method: post
  listAllClient:
    handler: src/client.listAllClient
    events:
      - httpApi:
          path: /client
          method: get
  getClient:
    handler: src/client.getClient
    events:
      - httpApi:
          path: /client/{id}
          method: get
  updateClient:
    handler: src/client.updateClient
    events:
      - httpApi:
          path: /client/{id}
          method: put
  deleteClient:
    handler: src/client.deleteClient
    events:
      - httpApi:
          path: /client/{id}
          method: delete

resources:
  Resources:
    ClienteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

