service: aws-lambda-crud-node
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: 'us-west-2'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:738618861152:table/ClientsTable

functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get
  createClient:
    handler: src/client/createClient.handler
    events:
      - httpApi:
          path: /client
          method: post
  listAllClient:
    handler: src/client/listAllClient.handler
    events:
      - httpApi:
          path: /client
          method: get
  getClient:
    handler: src/client/getClient.handler
    events:
      - httpApi:
          path: /client/{id}
          method: get
  updateClient:
    handler: src/client/updateClient.handler
    events:
      - httpApi:
          path: /client/{id}
          method: put
  deleteClient:
    handler: src/client/deleteClient.handler
    events:
      - httpApi:
          path: /client/{id}
          method: delete
  sqsCreateClient:
    handler: src/clientSQS/createClient.handler
    events:
      - sqs:
          arn: arn:aws:sqs:us-west-2:738618861152:CreateClient
          batchSize: 10
          maximumBatchingWindow: 60
          functionResponseType: ReportBatchItemFailures 

resources:
  Resources:
    ClienteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ClientsTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-lift
